import type { Metadata } from "next";
import localFont from "next/font/local";
import { GoogleOAuthProvider } from '@react-oauth/google';
import "./globals.css";
import { AuthProvider } from "@/context/authContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <AuthProvider>
    <html lang="en">
      <GoogleOAuthProvider clientId="122876537399-t7l16oldiln8eill19a5gsr9m3va02ru.apps.googleusercontent.com">
        
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          {children}
        </body>
      </GoogleOAuthProvider>
    </html>
    // </AuthProvider>
  );
}
